# reference: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "@types/node"
          - "@typescript-eslint/*"
          - "@vercel/ncc"
          - "eslint"
          - "js-yaml"
          - "prettier"
          - "typescript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      "@actions":
        patterns:
          - "@actions/*"
