# reference: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "@vercel/ncc"
          - "eslint"
          - "js-yaml"
          - "prettier"
          - "typescript"
      production-dependencies:
        patterns:
          - "@actions/*"
          - "logfmt"
          - "md5"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
