# reference: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      major-actions:
        patterns:
          - "@actions/*"
        update-types:
          - "major"
      major-typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
        update-types:
          - "major"
      major-types:
        patterns:
          - "@types/*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
