name: Honeycomb Buildevents
author: Honeycomb
description: Trace GitHub Action workflows with Honeycomb

branding:
  icon: activity
  color: yellow

inputs:
  apikey:
    description: A Honeycomb API key - needed to send traces.
    required: true
  apihost:
    description: Defaults to https://api.honeycomb.io
    required: false
  dataset:
    description: The Honeycomb dataset to send traces to.
    required: true
  status:
    description: Status of the job or worfklow. Setting this signals when to end the trace.
    required: false
  trace-start:
    description: Unix timestamp to represent when the trace started. Not necessary for single job workflows. Send in final use of the action for multi-job workflows.
    required: false
  matrix-key:
    description: Set this to a key unique for this matrix cell, only useful when using a build matrix.
    required: false
  job-status:
    description: Deprecated value - please use status instead
    deprecationMessage: job-status is now deprecated - please use status instead
  send-init-event:
    default: "true"
    description: (true/false) Whether to send an event representing the setup of this action.
    required: false

# outputs

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
