name: Honeycomb Buildevents
author: Koenraad Verheyden
description: Trace GitHub Action workflows with Honeycomb

branding:
  icon: activity
  color: yellow

inputs:
  apikey:
    description: API key used to communicate with the Honeycomb API.
    required: true
  dataset:
    description: Honeycomb dataset to use.
    required: true
  job-status:
    description: The job status.
    required: true
  matrix-key:
    description: Set this to a key unique for this matrix cell.
    required: false

#outputs:

runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
