name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Record job start
        run: |
          echo "JOB_ID=$(openssl rand -hex 8)" >> ${GITHUB_ENV}
          echo "JOB_START=$(date +%s)" >> ${GITHUB_ENV}
      - uses: honeycombio/gha-buildevents@v4
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          status: ${{ job.status }}

      - uses: actions/checkout@v6

      - run: buildevents cmd $TRACE_ID $JOB_ID 'install deps' -- npm ci
      - run: buildevents cmd $TRACE_ID $JOB_ID 'lint' -- npm run lint
      - run: buildevents cmd $TRACE_ID $JOB_ID 'format-check' -- npm run format-check
      - run: buildevents cmd $TRACE_ID $JOB_ID 'build' -- npm run build
      - run: buildevents cmd $TRACE_ID $JOB_ID 'pack' -- npm run pack
      - name: Verify no changes were made
        run: |
          buildevents cmd $TRACE_ID $JOB_ID 'verify-no-changes' -- \
            bash -c 'if ! git diff --quiet; then echo "Changes detected! Please run npm run all before committing code changes."; exit 1; fi'
      - name: Send parent span for job
        if: ${{ always() }} # to ensure parent span is sent when there are failed steps
        run: |
          buildevents step $TRACE_ID $JOB_ID $JOB_START 'CI'
